# Generated by Django 5.2.5 on 2025-10-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('IdCargos', models.AutoField(db_column='IdCargos', primary_key=True, serialize=False)),
                ('TipoDeCargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Bodeguero', 'Bodeguero')], db_column='TipoDeCargo', max_length=55, verbose_name='Tipo de cargo')),
                ('EstadoDelCargo', models.CharField(db_column='EstadoDelCargo', max_length=45, verbose_name='Estado del cargo')),
            ],
            options={
                'db_table': 'Cargos',
            },
        ),
    ]
