# Generated by Django 5.2.5 on 2025-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('Rut', models.CharField(db_column='RutEmpleado', max_length=15, primary_key=True, serialize=False)),
                ('NombreEmpleado', models.CharField(db_column='NombreEmpleado', max_length=55, verbose_name='Nombre')),
                ('ApellidoEmpleado', models.CharField(db_column='ApellidoEmpleado', max_length=55, verbose_name='Apellido')),
                ('EdadEmpleado', models.IntegerField(db_column='EdadEmpleado', verbose_name='Edad')),
                ('NumeroTelefonoEmpleado', models.IntegerField(db_column='NumeroTelefonoEmpleado', verbose_name='Telefono')),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
