# Generated by Django 5.2.5 on 2025-10-18 22:54

import CrudEmpleadosApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('IdEmpleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('RutEmpleado', models.CharField(db_column='RutEmpleado', error_messages={'unique': 'El rut ingresado ya se encuentra registrado, Por favor, verifique.'}, max_length=10, validators=[CrudEmpleadosApp.models.Empleados.validacion_rut_real], verbose_name='Rut (01234567-k)')),
                ('NombreEmpleado', models.CharField(db_column='NombreEmpleado', max_length=20, validators=[CrudEmpleadosApp.models.Empleados.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(2, message='Por favor, ingrese un nombre real')], verbose_name='Nombre')),
                ('ApellidoEmpleado', models.CharField(db_column='ApellidoEmpleado', max_length=55, validators=[CrudEmpleadosApp.models.Empleados.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(2, message='Por favor, ingrese un apellido real')], verbose_name='Apellido')),
                ('EdadEmpleado', models.IntegerField(db_column='EdadEmpleado', validators=[django.core.validators.MinValueValidator(18, message='Debes tener al menos 18 años'), django.core.validators.MaxValueValidator(99, message='Edad invalida, no puede tener mas de 100 años')], verbose_name='Edad')),
                ('NumeroTelefonoEmpleado', models.IntegerField(db_column='NumeroTelefonoEmpleado', validators=[django.core.validators.MinLengthValidator(9, message='Debes ingresar la numeracion correcta (912345678)')], verbose_name='Telefono (912345678)')),
            ],
            options={
                'db_table': 'Empleados',
                'constraints': [models.UniqueConstraint(fields=('IdEmpleado',), name='unique_id_empleado'), models.UniqueConstraint(fields=('RutEmpleado',), name='unique_rut_empleado')],
            },
        ),
    ]
