# Generated by Django 5.2.5 on 2025-10-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('IdEmpleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('RutEmpleado', models.CharField(db_column='RutEmpleado', max_length=12, verbose_name='Rut (01234567-k)')),
                ('NombreEmpleado', models.CharField(db_column='NombreEmpleado', max_length=55, verbose_name='Nombre')),
                ('ApellidoEmpleado', models.CharField(db_column='ApellidoEmpleado', max_length=55, verbose_name='Apellido')),
                ('EdadEmpleado', models.IntegerField(db_column='EdadEmpleado', verbose_name='Edad')),
                ('NumeroTelefonoEmpleado', models.IntegerField(db_column='NumeroTelefonoEmpleado', verbose_name='Telefono (912345678)')),
            ],
            options={
                'db_table': 'Empleados',
                'constraints': [models.UniqueConstraint(fields=('IdEmpleado',), name='unique_id_empleado'), models.UniqueConstraint(fields=('RutEmpleado',), name='unique_rut_empleado')],
            },
        ),
    ]
