# Generated by Django 5.2.5 on 2025-10-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('IdBodega', models.AutoField(db_column='IdBodega', primary_key=True, serialize=False, verbose_name='Id Bodega')),
                ('NombreBodega', models.CharField(db_column='NombreBodega', max_length=55, verbose_name='Nombre')),
                ('UbicacionBodega', models.CharField(db_column='UbicacionBodega', max_length=65, verbose_name='Ubicacion')),
            ],
            options={
                'db_table': 'Bodegas',
                'constraints': [models.UniqueConstraint(fields=('IdBodega',), name='unique_id_bodega')],
            },
        ),
    ]
