# Generated by Django 5.2.5 on 2025-11-16 00:27

import CrudBodegasApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('IdBodega', models.AutoField(db_column='IdBodega', primary_key=True, serialize=False, verbose_name='Id Bodega')),
                ('NombreBodega', models.CharField(db_column='NombreBodega', max_length=20, validators=[CrudBodegasApp.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(5, message='Debes ingresar minimo 5 caracteres')], verbose_name='Nombre')),
                ('UbicacionBodega', models.CharField(db_column='UbicacionBodega', max_length=30, validators=[CrudBodegasApp.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(5, message='Debes ingresar minimo 5 caracteres')], verbose_name='Ubicacion')),
                ('EstadoBodega', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('En Mantenimiento', 'En Mantenimiento')], db_column='EstadoBodega', max_length=20, verbose_name='Estado de la bodega')),
                ('ObservacionesBodega', models.TextField(db_column='ObservacionesBodega', max_length=500, validators=[CrudBodegasApp.models.Bodegas.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar mínimo 10 caracteres')], verbose_name='Observaciones sobre la bodega')),
            ],
            options={
                'db_table': 'Bodegas',
                'constraints': [models.UniqueConstraint(fields=('IdBodega',), name='unique_id_bodega')],
            },
        ),
    ]
