# Generated by Django 5.2.5 on 2025-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudBodegasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegas',
            name='UbicacionBodega',
            field=models.CharField(db_column='UbicacionBodega', max_length=65, verbose_name='Ubicacion'),
        ),
    ]
