-- MySQL Script generated by MySQL Workbench
-- Sat Oct  4 17:59:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema punto-de-venta-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema punto-de-venta-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `punto-de-venta-db` DEFAULT CHARACTER SET utf8 ;
USE `punto-de-venta-db` ;

-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`Productos` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `CodigoDeBarras` VARCHAR(100) NOT NULL,
  `ValorProducto` INT NOT NULL,
  `StockProducto` INT NOT NULL,
  `NombreProducto` VARCHAR(60) NOT NULL,
  `FechaDeRegistroProducto` TIMESTAMP NOT NULL,
  `MarcaProducto` VARCHAR(55) NOT NULL,
  `FechaDeVencimiento` DATETIME NOT NULL,
  PRIMARY KEY (`IdProducto`),
  UNIQUE INDEX `idProductos_UNIQUE` (`IdProducto` ) ,
  UNIQUE INDEX `CodigoDeBarras_UNIQUE` (`CodigoDeBarras` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`Empleados` (
  `RutEmpleado` INT NOT NULL,
  `NombreEmpleado` VARCHAR(55) NOT NULL,
  `ApellidoEmpleado` VARCHAR(55) NOT NULL,
  `EdadEmpleado` INT NOT NULL,
  `NumeroTelefonoEmpleado` INT NOT NULL,
  PRIMARY KEY (`RutEmpleado`),
  UNIQUE INDEX `RutEmpleado_UNIQUE` (`RutEmpleado` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`Usuarios` (
  `IdUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUsuarios`),
  UNIQUE INDEX `IdUsuarios_UNIQUE` (`IdUsuarios` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`Bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`Bodegas` (
  `IdBodega` INT NOT NULL AUTO_INCREMENT,
  `NombreBodega` VARCHAR(55) NOT NULL,
  `UbicacionBodega` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`IdBodega`),
  UNIQUE INDEX `NombreBodega_UNIQUE` (`NombreBodega` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`Cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`Cargos` (
  `IdCargos` INT NOT NULL AUTO_INCREMENT,
  `TipoDeCargo` ENUM('Gerente', 'Bodeguero') NOT NULL,
  `EstadoDelCargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`CategoriaBodegaUusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`CategoriaBodegaUusuario` (
  `IdAccionesBodega` INT NOT NULL AUTO_INCREMENT,
  `FechaAccionBodega` TIMESTAMP NOT NULL,
  `AccionBodega` ENUM('Agregar', 'Editar', 'Eliminar') NOT NULL,
  PRIMARY KEY (`IdAccionesBodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`AccionesProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`AccionesProductos` (
  `IdAccionesProductos` INT NOT NULL AUTO_INCREMENT,
  `FechaAccionProductos` TIMESTAMP NOT NULL,
  `AccionProductos` ENUM('Registrar', 'Editar', 'Eliminar') NOT NULL,
  PRIMARY KEY (`IdAccionesProductos`),
  UNIQUE INDEX `Accion_UNIQUE` (`AccionProductos` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`timestamps_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`timestamps_1` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`CategoriaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`CategoriaProducto` (
  `IdCategoriaProducto` INT NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`IdCategoriaProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`AccionCategoriaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`AccionCategoriaProducto` (
  `IdAccionCategoriaProducto` INT NOT NULL,
  `FechaAccionCategoriaProducto` TIMESTAMP NOT NULL,
  `AccionCategoriaProducto` ENUM('Registrar', 'Editar', 'Eliminar') NOT NULL,
  PRIMARY KEY (`IdAccionCategoriaProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`AccionCategoriaBodegaUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`AccionCategoriaBodegaUsuario` (
  `IdAccionnCategoriaBodegaUsuario` INT NOT NULL,
  `FechaAccionnCategoriaBodegaUsuario` TIMESTAMP NOT NULL,
  `AccionnCategoriaBodegaUsuario` ENUM('Registrar', 'Editar', 'Eliminar') NOT NULL,
  PRIMARY KEY (`IdAccionnCategoriaBodegaUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `punto-de-venta-db`.`AccionBodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `punto-de-venta-db`.`AccionBodega` (
  `IdAccionBodega` INT NOT NULL,
  `FechaAccionBodega` TIMESTAMP NOT NULL,
  `AccionBodega` ENUM('Registrar', 'Editar', 'Eliminar') NOT NULL,
  PRIMARY KEY (`IdAccionBodega`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
