# Generated by Django 5.2.5 on 2025-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('CodigoDeBarras', models.CharField(db_column='CodigoDeBarras', max_length=100, verbose_name='Código de Barras')),
                ('ValorProducto', models.IntegerField(db_column='ValorProducto', verbose_name='Valor')),
                ('StockProducto', models.IntegerField(db_column='StockProducto', verbose_name='Stock')),
                ('NombreProducto', models.CharField(db_column='NombreProducto', max_length=60, verbose_name='Nombre del producto')),
                ('FechaDeRegistroProducto', models.DateTimeField(auto_now_add=True, db_column='FechaDeRegistroProducto')),
                ('MarcaProducto', models.CharField(db_column='MarcaProducto', max_length=55, verbose_name='Marca')),
                ('FechaDeVencimiento', models.DateField(db_column='FechaDeVencimiento', verbose_name='Fecha de vencimiento')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
    ]
