# Generated by Django 5.2.5 on 2025-10-19 17:58

import CrudProductosApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IdProducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('CodigoDeBarras', models.CharField(db_column='CodigoDeBarras', error_messages={'unique': 'El código de barras ingresado ya se encuentra registrado. Por favor, verifique.'}, max_length=100, verbose_name='Código de Barras')),
                ('ValorProducto', models.IntegerField(db_column='ValorProducto', validators=[django.core.validators.MinValueValidator(1000, message='El valor minimo de un producto es de $1000')], verbose_name='Valor')),
                ('StockProducto', models.IntegerField(db_column='StockProducto', validators=[django.core.validators.MinValueValidator(1, message='El Stock minimo es de 1 unidad ')], verbose_name='Stock')),
                ('NombreProducto', models.CharField(db_column='NombreProducto', max_length=60, validators=[django.core.validators.MinLengthValidator(5, message='El nombre del producto debe tener al menos 5 caracteres.')], verbose_name='Nombre del producto')),
                ('FechaDeRegistroProducto', models.DateTimeField(auto_now_add=True, db_column='FechaDeRegistroProducto')),
                ('MarcaProducto', models.CharField(db_column='MarcaProducto', max_length=55, validators=[django.core.validators.MinLengthValidator(4, message='La marca del producto debe tener al menos 4 caracteres')], verbose_name='Marca')),
                ('FechaDeVencimiento', models.DateField(db_column='FechaDeVencimiento', validators=[CrudProductosApp.models.Productos.validacion_fecha_de_vencimiento_futura], verbose_name='Fecha de vencimiento')),
            ],
            options={
                'db_table': 'Productos',
                'constraints': [models.UniqueConstraint(fields=('IdProducto',), name='unique_id_producto'), models.UniqueConstraint(fields=('CodigoDeBarras',), name='unique_codigo_de_barras')],
            },
        ),
    ]
