# Generated by Django 5.2.5 on 2025-11-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrudBodegasApp', '0001_initial'),
        ('CrudCargosApp', '0001_initial'),
        ('CrudCategoriaProductoApp', '0001_initial'),
        ('CrudEmpleadosApp', '0001_initial'),
        ('CrudProductosApp', '0001_initial'),
        ('CrudUsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaBodega',
            fields=[
                ('IdAuditoriaBodega', models.AutoField(db_column='IdAuditoriaBodega', primary_key=True, serialize=False)),
                ('BodegaIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('BodegaNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Bodega', models.ForeignKey(blank=True, db_column='BodegaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_bodegas', to='CrudBodegasApp.bodegas')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_bodega_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaBodega',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaBodega',), name='unique_id_auditoria_bodega')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCargo',
            fields=[
                ('IdAuditoriaCargo', models.AutoField(db_column='IdAuditoriaCargo', primary_key=True, serialize=False)),
                ('CargoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('CargoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Cargo', models.ForeignKey(blank=True, db_column='CargoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_cargos', to='CrudCargosApp.cargos')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_cargo_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaCargo',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaCargo',), name='unique_id_auditoria_cargo')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCategoria',
            fields=[
                ('IdAuditoriaCategoria', models.AutoField(db_column='IdAuditoriaCategoria', primary_key=True, serialize=False)),
                ('CategoriaIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('CategoriaNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Categoria', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_categoria', to='CrudCategoriaProductoApp.categoriaproducto')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_categoria_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaCategoria',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaCategoria',), name='unique_id_auditoria_categoria')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpleado',
            fields=[
                ('IdAuditoriaEmpleado', models.AutoField(db_column='IdAuditoriaEmpleado', primary_key=True, serialize=False)),
                ('EmpleadoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('EmpleadoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Empleado', models.ForeignKey(blank=True, db_column='EmpleadoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_empleado', to='CrudEmpleadosApp.empleados')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_empleado_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaEmpleado',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaEmpleado',), name='unique_id_auditoria_empleado')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('IdAuditoriaProducto', models.AutoField(db_column='IdAuditoriaProducto', primary_key=True, serialize=False)),
                ('ProductoIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('ProductoNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Producto', models.ForeignKey(blank=True, db_column='ProductoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_producto', to='CrudProductosApp.productos')),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_producto_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaProducto',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaProducto',), name='unique_id_auditoria_producto')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('IdAuditoriaUsuario', models.AutoField(db_column='IdAuditoriaUsuario', primary_key=True, serialize=False)),
                ('UsuarioIdRespaldo', models.IntegerField(blank=True, null=True)),
                ('UsuarioNombreRespaldo', models.CharField(blank=True, max_length=70, null=True)),
                ('Accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('MOVIMIENTO', 'Movimiento de stock')], max_length=50)),
                ('Fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_usuario_usuario', to='CrudUsuariosApp.usuarios')),
            ],
            options={
                'db_table': 'AuditoriaUsuario',
                'constraints': [models.UniqueConstraint(fields=('IdAuditoriaUsuario',), name='unique_id_auditoria_usuario')],
            },
        ),
    ]
