# Generated by Django 5.2.5 on 2025-10-18 22:54

import CrudUsuariosApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('Username', models.CharField(db_column='Username', error_messages={'unique': 'El username ingresado ya se encuentra ocupado, Por favor, Intentelo con otro nuevamente.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(5, message='El username debe tener al menos 5 caracteres')])),
                ('Password', models.CharField(db_column='Password', max_length=45, validators=[CrudUsuariosApp.models.Usuarios.validacion_password_segura, django.core.validators.MinLengthValidator(5, message='La password debe tener al menos 5 caracteres')])),
            ],
            options={
                'db_table': 'Usuarios',
                'constraints': [models.UniqueConstraint(fields=('IdUsuarios',), name='unique_id_usuarios'), models.UniqueConstraint(fields=('Username',), name='unique_username')],
            },
        ),
    ]
