# Generated by Django 5.2.5 on 2025-10-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('Username', models.CharField(db_column='Username', max_length=30)),
                ('Password', models.CharField(db_column='Password', max_length=45)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
