# Generated by Django 5.2.5 on 2025-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuarios', models.IntegerField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('ContrasenaUsuario', models.CharField(db_column='ContrasenaUsuario', max_length=45)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
