# Generated by Django 5.2.5 on 2025-11-03 02:12

import CrudCategoriaProductoApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('IdCategoriaProducto', models.AutoField(db_column='IdCategoriaProducto', primary_key=True, serialize=False, verbose_name='Id Categoria Producto')),
                ('NombreCategoria', models.CharField(db_column='NombreCategoria', max_length=20, validators=[CrudCategoriaProductoApp.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(3, message='Debes ingresar minimo 3 caracteres')], verbose_name='Nombre de la categoria')),
                ('Descripcion', models.TextField(db_column='Descripcion', max_length=500, validators=[CrudCategoriaProductoApp.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar minimo 10 caracteres')], verbose_name='Descripcion')),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Pausado', 'Pausado')], db_column='Estado', max_length=10)),
                ('Observaciones', models.TextField(db_column='Observaciones', max_length=500, validators=[CrudCategoriaProductoApp.models.CategoriaProducto.validacion_no_caracteres_especiales, django.core.validators.MinLengthValidator(10, message='Debes ingresar minimo 10 caracteres')], verbose_name='Observaciones')),
            ],
            options={
                'db_table': 'CategoriaProducto',
                'constraints': [models.UniqueConstraint(fields=('IdCategoriaProducto',), name='unique_id_categoria_producto')],
            },
        ),
    ]
