# Generated by Django 5.2.5 on 2025-10-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('IdCategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(db_column='NombreCategoria', max_length=55, verbose_name='Nombre')),
                ('DescripcionCategoria', models.CharField(db_column='DescripcionCategoria', max_length=65, verbose_name='Descripcion')),
            ],
        ),
    ]
